### ISSUE TITLE
Incorrect database server version, check compiler options

### ISSUE THREAD

**Issue by arvanus** [lalexs75/FBManager#29]
Hi, I downloaded FBManager installer, installed without problems, but when I try to connect to a Firebird 2.5 DB, FBManager raises this error:

> Incorrect database server version, check compiler options

I'm using W10
Any idea of what could be?
Thanks

**Comment by lalexs75** [comment]
Current version need fbclient from FB 3.0

**Comment by arvanus** [comment]
Hi, I'm using fbclient.dll v. 3.0.4 
![image](https://user-images.githubusercontent.com/8182958/69483817-dbe68180-0e0a-11ea-9293-cd5c651d5b5b.png)

**Comment by lalexs75** [comment]
It’s strange. I will check it.

**Comment by arvanus** [comment]
Hi, and simply copied fbclient.dll to FBManager folder, and now is connecting.
I found that I have an old fbclient.dll v. 2.5.9 at C:\Windows\SysWOW64
Probably FBManager are ignoring the registration parameter, is it possible?
Thanks!

**Comment by lalexs75** [comment]
Thanks. I will check. Maybe there really is a mistake. In this configuration, I have not tested.

**Comment by lalexs75** [comment]
Please test windows version.
i'm include to distributive FB3 client libs.

**Comment by arvanus** [comment]
I uninstalled and tested, worked fine!
Thanks
