### ISSUE TITLE
INSTEAD OF triggers on views doesn't allowing

### ISSUE THREAD

**Issue by Megadragon** [lalexs75/FBManager#38]
Интерфейс создания триггеров не даёт выбирать `INSTEAD OF` на представления (`VIEW`), хотя, судя по [документации](https://www.postgresql.org/docs/current/trigger-definition.html), такие триггера вполне позволительны.

**Comment by lalexs75** [comment]
Спасибо.
Проверю.

**Comment by lalexs75** [comment]
Доработал.
Теперь можно на представление вешать тригера.
Функционал будет в ночной сборке. 
Можно тестировать и закрывать вопрос, если всё нормально.
