### ISSUE TITLE
Menu item captions are not updated correctly.

### ISSUE THREAD

**Issue by peha84** [lalexs75/FBManager#43]
Menu item captions are not updated correctly. But when you click on the items, it does what you need. Just the names are not updated.
Details on the screenshots.

Screenshot 1:
![Screenshot 1](https://imagizer.imageshack.com/img924/4939/9ynLqT.png)

Screenshot 2:
![Screenshot 2](https://imagizer.imageshack.com/img922/1926/MyJFH4.png)

**Comment by peha84** [comment]
Version: 0.11.2.5593
![Version](http://imageshack.com/a/img922/6439/5onTiG.png)

**Comment by lalexs75** [comment]
tnx for bugreport.

**Comment by lalexs75** [comment]
fixed in rev. 0dd3529
