### ISSUE TITLE
PG: Displays incorrect data

### ISSUE THREAD

**Issue by peha84** [lalexs75/FBManager#50]
I have a table. It has several thousand entries. When viewing data and sorting it, the countdown does not begin with the most recent record:
![0001](https://user-images.githubusercontent.com/20636769/76744537-0d4dd900-677d-11ea-932c-53d69f1b4de3.png)

If I execute a SQL query (SELECT max(id_z.....) FROM table), then the result:
![0002](https://user-images.githubusercontent.com/20636769/76744623-34a4a600-677d-11ea-8adc-fb8a049ac51d.png)

**Comment by peha84** [comment]
This program send SQL:
`select * from table order by id_z..... limit 1000 `

If I sort by column, the query does not change and is sorted within the first thousand records.
Is it possible to change the request itself when sorting?
eg:
`select * from table order by id_z..... limit 1000` **`DESC`**

**Comment by lalexs75** [comment]
For tables, 1000 records are selected by default. You can change it in the Count row to fetch field or in the system settings.
A full sample of data during re-sorting can take up too much time / memory. I do not really like this idea.

**Comment by peha84** [comment]
If I click on sorting in descending order, I want to see the last 1000 entries. But the program sorts the first 1000 in descending order.

**Comment by lalexs75** [comment]
At the moment, sorting occurs only in the data that is already fetched. And this is the first 1000.
I’ll think about how to make a new request with other parameters.

**Comment by peha84** [comment]
Really miss this, thanks

**Comment by lalexs75** [comment]
Tomorrow's assembly should work.
