### ISSUE TITLE
Положение окна программы

### ISSUE THREAD

**Issue by Megadragon** [lalexs75/FBManager#6]
Не сохраняется положение главного окна программы между запусками. Вместо этого, окно автоматически растягивается по размеру экрана, устанавливая `WindowState = wsNormal` вместо `wsMaximized`.
Вдобавок, при левом размещении Панели задач Windows (вместо нижнего по умолчанию) окно при запуске частично прячется за неё.
Приходится при каждом запуске программы нажимать `Win + вверх`, что раздражает.
Проверено на Windows 7 SP1 x64 и мониторе `1920x1080`.

**Comment by lalexs75** [comment]
А если сделать всегда wsMaximized - так лучше будет? Я уже не помню - почему вручную устанавливаю размер во весь экран.

**Comment by lalexs75** [comment]
Исправил. Был когдато костыль для обработки несколькомниторных конфигурацйий. Протестировал на Win7 - вроде нормально.

**Comment by Megadragon** [comment]
Ещё вариант: сохранять при закрытии окна и, соответственно, восстанавливать при открытии не только координаты, а и `WindowState`.

**Comment by lalexs75** [comment]
Я не стал заморачиваться с сохранением рамеров. Изначально так было - но не удобно оказалось. После старта программы у пользователя обычно ожидание увидеть именно программу. И он не помнит, в каком состоянии она была закрыта (это основываясь на моём опыте по другим программам). Поэтому легче открыть программу на весь экран, чем заставить пользователя искать её в куче других открытых окон.
Теоретически можно сделать настроку поведения - но надо ли?
